import { generateAxiosResponseObject } from '../../../utils/helper';
import { RiotAPI } from '../../riotgames';

const riotAPI: RiotAPI = {
  users: {
    get: jest.fn(async () => generateAxiosResponseObject({
      data: {
        accountId: '123',
        id: '234',
        summonerLevel: 271,
        name: 'TEEHEE92',
        profileIconId: 123,
        puuid: '123',
        revisionDate: 1616226785000,
        matches: [
          {
            championImg: 'Anivia.png',
            role: 'DUO_SUPPORT',
            platformId: 'NA1',
            queue: 450,
            lane: 'MID',
            gameId: 3833657566,
            timestamp: 1616225321603,
            season: 13,
            champion: 34,
          },
        ],
      },
    })),
  },
  matchList: {
    get: jest.fn(),
  },
  patch: {
    version: {
      get: jest.fn(async () => generateAxiosResponseObject({ data: ['0'] }, { status: 200 })),
    },
    data: {
      get: jest.fn(async () => generateAxiosResponseObject({
        data: {
          type: 'champion',
          format: 'standAloneComplex',
          version: '11.5.1',
          data: {
            Aatrox: {
              version: '11.5.1',
              id: 'Aatrox',
              key: '266',
              name: 'Aatrox',
              title: 'the Darkin Blade',
              blurb:
                  'Once honored defenders of Shurima against the Void, Aatrox and his brethren would eventually become an even greater threat to Runeterra, and were defeated only by cunning mortal sorcery. But after centuries of imprisonment, Aatrox was the first to find...',
              info: {
                attack: 8,
                defense: 4,
                magic: 3,
                difficulty: 4,
              },
              image: {
                full: 'Aatrox.png',
                sprite: 'champion0.png',
                group: 'champion',
                x: 0,
                y: 0,
                w: 48,
                h: 48,
              },
              tags: ['Fighter', 'Tank'],
              partype: 'Blood Well',
              stats: {
                hp: 580,
                hpperlevel: 90,
                mp: 0,
                mpperlevel: 0,
                movespeed: 345,
                armor: 38,
                armorperlevel: 3.25,
                spellblock: 32,
                spellblockperlevel: 1.25,
                attackrange: 175,
                hpregen: 3,
                hpregenperlevel: 1,
                mpregen: 0,
                mpregenperlevel: 0,
                crit: 0,
                critperlevel: 0,
                attackdamage: 60,
                attackdamageperlevel: 5,
                attackspeedperlevel: 2.5,
                attackspeed: 0.651,
              },
            },
          },
        },
      })),
    },
  },
  match: {
    overview: {
      get: jest.fn(async () => generateAxiosResponseObject({
        data: {
          gameId: 3813810489,
          platformId: 'NA1',
          gameCreation: 1615019688009,
          gameDuration: 1190,
          queueId: 900,
          mapId: 11,
          seasonId: 13,
          gameVersion: '11.5.361.3108',
          gameMode: 'URF',
          gameType: 'MATCHED_GAME',
          teams: [
            {
              teamId: 100,
              win: 'Fail',
              firstBlood: true,
              firstTower: false,
              firstInhibitor: false,
              firstBaron: true,
              firstDragon: false,
              firstRiftHerald: false,
              towerKills: 0,
              inhibitorKills: 0,
              baronKills: 1,
              dragonKills: 1,
              vilemawKills: 0,
              riftHeraldKills: 0,
              dominionVictoryScore: 0,
              bans: [],
            },
            {
              teamId: 200,
              win: 'Win',
              firstBlood: false,
              firstTower: true,
              firstInhibitor: true,
              firstBaron: false,
              firstDragon: true,
              firstRiftHerald: false,
              towerKills: 9,
              inhibitorKills: 3,
              baronKills: 0,
              dragonKills: 3,
              vilemawKills: 0,
              riftHeraldKills: 0,
              dominionVictoryScore: 0,
              bans: [],
            },
          ],
          participants: [
            {
              participantId: 1,
              teamId: 100,
              championId: 96,
              spell1Id: 6,
              spell2Id: 4,
              stats: {
                participantId: 1,
                win: false,
                item0: 1056,
                item1: 6653,
                item2: 3020,
                item3: 3157,
                item4: 3089,
                item5: 0,
                item6: 3513,
                kills: 8,
                deaths: 10,
                assists: 5,
                largestKillingSpree: 2,
                largestMultiKill: 2,
                killingSprees: 3,
                longestTimeSpentLiving: 472,
                doubleKills: 2,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 99629,
                magicDamageDealt: 87118,
                physicalDamageDealt: 8033,
                trueDamageDealt: 4476,
                largestCriticalStrike: 0,
                totalDamageDealtToChampions: 22492,
                magicDamageDealtToChampions: 19434,
                physicalDamageDealtToChampions: 1009,
                trueDamageDealtToChampions: 2048,
                totalHeal: 3679,
                totalUnitsHealed: 1,
                damageSelfMitigated: 7944,
                damageDealtToObjectives: 14932,
                damageDealtToTurrets: 324,
                visionScore: 26,
                timeCCingOthers: 13,
                totalDamageTaken: 22723,
                magicalDamageTaken: 12097,
                physicalDamageTaken: 9492,
                trueDamageTaken: 1133,
                goldEarned: 14592,
                goldSpent: 11300,
                turretKills: 0,
                inhibitorKills: 0,
                totalMinionsKilled: 59,
                neutralMinionsKilled: 24,
                neutralMinionsKilledTeamJungle: 19,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 402,
                champLevel: 17,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 18,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8128,
                perk0Var1: 936,
                perk0Var2: 17,
                perk0Var3: 0,
                perk1: 8139,
                perk1Var1: 1657,
                perk1Var2: 0,
                perk1Var3: 0,
                perk2: 8138,
                perk2Var1: 30,
                perk2Var2: 0,
                perk2Var3: 0,
                perk3: 8135,
                perk3Var1: 1422,
                perk3Var2: 4,
                perk3Var3: 0,
                perk4: 9111,
                perk4Var1: 1272,
                perk4Var2: 260,
                perk4Var3: 0,
                perk5: 8299,
                perk5Var1: 837,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8100,
                perkSubStyle: 8000,
                statPerk0: 5008,
                statPerk1: 5002,
                statPerk2: 5001,
              },
              timeline: {
                participantId: 1,
                creepsPerMinDeltas: {
                  '0-10': 3.9,
                },
                xpPerMinDeltas: {
                  '0-10': 388.4,
                },
                goldPerMinDeltas: {
                  '0-10': 520.2,
                },
                csDiffPerMinDeltas: {
                  '0-10': 0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': -15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 598.8,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': -154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 2,
              teamId: 100,
              championId: 222,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                participantId: 2,
                win: false,
                item0: 6672,
                item1: 3006,
                item2: 3085,
                item3: 3094,
                item4: 3031,
                item5: 1053,
                item6: 3364,
                kills: 6,
                deaths: 10,
                assists: 11,
                largestKillingSpree: 3,
                largestMultiKill: 2,
                killingSprees: 1,
                longestTimeSpentLiving: 250,
                doubleKills: 1,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 92156,
                magicDamageDealt: 3094,
                physicalDamageDealt: 84484,
                trueDamageDealt: 4578,
                largestCriticalStrike: 466,
                totalDamageDealtToChampions: 19268,
                magicDamageDealtToChampions: 897,
                physicalDamageDealtToChampions: 16813,
                trueDamageDealtToChampions: 1557,
                totalHeal: 3787,
                totalUnitsHealed: 1,
                damageSelfMitigated: 9124,
                damageDealtToObjectives: 6893,
                damageDealtToTurrets: 0,
                visionScore: 6,
                timeCCingOthers: 21,
                totalDamageTaken: 21865,
                magicalDamageTaken: 9477,
                physicalDamageTaken: 11303,
                trueDamageTaken: 1084,
                goldEarned: 14357,
                goldSpent: 13900,
                turretKills: 0,
                inhibitorKills: 0,
                totalMinionsKilled: 111,
                neutralMinionsKilled: 7,
                neutralMinionsKilledTeamJungle: 3,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 115,
                champLevel: 17,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 1,
                wardsKilled: 1,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8008,
                perk0Var1: 2,
                perk0Var2: 20,
                perk0Var3: 0,
                perk1: 9111,
                perk1Var1: 575,
                perk1Var2: 340,
                perk1Var3: 0,
                perk2: 9104,
                perk2Var1: 10,
                perk2Var2: 30,
                perk2Var3: 0,
                perk3: 8014,
                perk3Var1: 527,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8139,
                perk4Var1: 1165,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8135,
                perk5Var1: 2527,
                perk5Var2: 5,
                perk5Var3: 0,
                perkPrimaryStyle: 8000,
                perkSubStyle: 8100,
                statPerk0: 5005,
                statPerk1: 5008,
                statPerk2: 5003,
              },
              timeline: {
                participantId: 2,
                creepsPerMinDeltas: {
                  '0-10': 6.6,
                },
                xpPerMinDeltas: {
                  '0-10': 550,
                },
                goldPerMinDeltas: {
                  '0-10': 646.4,
                },
                csDiffPerMinDeltas: {
                  '0-10': 0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': -15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 584.1,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': -154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 3,
              teamId: 100,
              championId: 22,
              spell1Id: 4,
              spell2Id: 21,
              stats: {
                participantId: 3,
                win: false,
                item0: 1055,
                item1: 3157,
                item2: 3158,
                item3: 4636,
                item4: 4628,
                item5: 1058,
                item6: 3364,
                kills: 3,
                deaths: 8,
                assists: 17,
                largestKillingSpree: 3,
                largestMultiKill: 2,
                killingSprees: 1,
                longestTimeSpentLiving: 489,
                doubleKills: 1,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 56712,
                magicDamageDealt: 17315,
                physicalDamageDealt: 38748,
                trueDamageDealt: 649,
                largestCriticalStrike: 145,
                totalDamageDealtToChampions: 21832,
                magicDamageDealtToChampions: 13206,
                physicalDamageDealtToChampions: 7976,
                trueDamageDealtToChampions: 649,
                totalHeal: 150,
                totalUnitsHealed: 1,
                damageSelfMitigated: 11000,
                damageDealtToObjectives: 3507,
                damageDealtToTurrets: 543,
                visionScore: 28,
                timeCCingOthers: 48,
                totalDamageTaken: 17860,
                magicalDamageTaken: 7912,
                physicalDamageTaken: 9372,
                trueDamageTaken: 574,
                goldEarned: 12605,
                goldSpent: 12300,
                turretKills: 0,
                inhibitorKills: 0,
                totalMinionsKilled: 63,
                neutralMinionsKilled: 4,
                neutralMinionsKilledTeamJungle: 0,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 448,
                champLevel: 17,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 13,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8229,
                perk0Var1: 2006,
                perk0Var2: 0,
                perk0Var3: 0,
                perk1: 8224,
                perk1Var1: 660,
                perk1Var2: 0,
                perk1Var3: 0,
                perk2: 8233,
                perk2Var1: 12,
                perk2Var2: 20,
                perk2Var3: 0,
                perk3: 8236,
                perk3Var1: 48,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8126,
                perk4Var1: 663,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8106,
                perk5Var1: 5,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8200,
                perkSubStyle: 8100,
                statPerk0: 5008,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 3,
                creepsPerMinDeltas: {
                  '0-10': 3.8,
                },
                xpPerMinDeltas: {
                  '0-10': 387.5,
                },
                goldPerMinDeltas: {
                  '0-10': 595.1,
                },
                csDiffPerMinDeltas: {
                  '0-10': 0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': -15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 351.2,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': -154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 4,
              teamId: 100,
              championId: 236,
              spell1Id: 7,
              spell2Id: 4,
              stats: {
                participantId: 4,
                win: false,
                item0: 6672,
                item1: 3006,
                item2: 6676,
                item3: 3072,
                item4: 3036,
                item5: 3123,
                item6: 3340,
                kills: 11,
                deaths: 12,
                assists: 11,
                largestKillingSpree: 3,
                largestMultiKill: 2,
                killingSprees: 3,
                longestTimeSpentLiving: 237,
                doubleKills: 2,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 88015,
                magicDamageDealt: 2795,
                physicalDamageDealt: 78516,
                trueDamageDealt: 6703,
                largestCriticalStrike: 589,
                totalDamageDealtToChampions: 22271,
                magicDamageDealtToChampions: 963,
                physicalDamageDealtToChampions: 18788,
                trueDamageDealtToChampions: 2519,
                totalHeal: 2387,
                totalUnitsHealed: 3,
                damageSelfMitigated: 9144,
                damageDealtToObjectives: 3311,
                damageDealtToTurrets: 960,
                visionScore: 8,
                timeCCingOthers: 1,
                totalDamageTaken: 19341,
                magicalDamageTaken: 6501,
                physicalDamageTaken: 11803,
                trueDamageTaken: 1036,
                goldEarned: 15807,
                goldSpent: 14600,
                turretKills: 0,
                inhibitorKills: 0,
                totalMinionsKilled: 81,
                neutralMinionsKilled: 4,
                neutralMinionsKilledTeamJungle: 1,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 12,
                champLevel: 16,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 5,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8010,
                perk0Var1: 96,
                perk0Var2: 0,
                perk0Var3: 0,
                perk1: 9111,
                perk1Var1: 530,
                perk1Var2: 440,
                perk1Var3: 0,
                perk2: 9103,
                perk2Var1: 7,
                perk2Var2: 20,
                perk2Var3: 0,
                perk3: 8014,
                perk3Var1: 833,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8143,
                perk4Var1: 555,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8135,
                perk5Var1: 994,
                perk5Var2: 5,
                perk5Var3: 0,
                perkPrimaryStyle: 8000,
                perkSubStyle: 8100,
                statPerk0: 5005,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 4,
                creepsPerMinDeltas: {
                  '0-10': 4.7,
                },
                xpPerMinDeltas: {
                  '0-10': 331.5,
                },
                goldPerMinDeltas: {
                  '0-10': 732.8,
                },
                csDiffPerMinDeltas: {
                  '0-10': 0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': -15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 547.5999999999999,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': -154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 5,
              teamId: 100,
              championId: 2,
              spell1Id: 4,
              spell2Id: 6,
              stats: {
                participantId: 5,
                win: false,
                item0: 6630,
                item1: 3065,
                item2: 3075,
                item3: 3047,
                item4: 6333,
                item5: 0,
                item6: 3340,
                kills: 10,
                deaths: 11,
                assists: 9,
                largestKillingSpree: 3,
                largestMultiKill: 1,
                killingSprees: 2,
                longestTimeSpentLiving: 273,
                doubleKills: 0,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 65223,
                magicDamageDealt: 412,
                physicalDamageDealt: 51429,
                trueDamageDealt: 13381,
                largestCriticalStrike: 12,
                totalDamageDealtToChampions: 17716,
                magicDamageDealtToChampions: 94,
                physicalDamageDealtToChampions: 11257,
                trueDamageDealtToChampions: 6364,
                totalHeal: 4753,
                totalUnitsHealed: 1,
                damageSelfMitigated: 35053,
                damageDealtToObjectives: 839,
                damageDealtToTurrets: 101,
                visionScore: 1,
                timeCCingOthers: 15,
                totalDamageTaken: 27214,
                magicalDamageTaken: 9202,
                physicalDamageTaken: 13783,
                trueDamageTaken: 4228,
                goldEarned: 15181,
                goldSpent: 14950,
                turretKills: 0,
                inhibitorKills: 0,
                totalMinionsKilled: 56,
                neutralMinionsKilled: 8,
                neutralMinionsKilledTeamJungle: 0,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 262,
                champLevel: 16,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 0,
                wardsKilled: 0,
                firstBloodKill: true,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 1,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8010,
                perk0Var1: 495,
                perk0Var2: 0,
                perk0Var3: 0,
                perk1: 9111,
                perk1Var1: 861,
                perk1Var2: 380,
                perk1Var3: 0,
                perk2: 9104,
                perk2Var1: 7,
                perk2Var2: 20,
                perk2Var3: 0,
                perk3: 8014,
                perk3Var1: 448,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8139,
                perk4Var1: 1120,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8135,
                perk5Var1: 1317,
                perk5Var2: 4,
                perk5Var3: 0,
                perkPrimaryStyle: 8000,
                perkSubStyle: 8100,
                statPerk0: 5005,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 5,
                creepsPerMinDeltas: {
                  '0-10': 3.2,
                },
                xpPerMinDeltas: {
                  '0-10': 459.4,
                },
                goldPerMinDeltas: {
                  '0-10': 717.5999999999999,
                },
                csDiffPerMinDeltas: {
                  '0-10': 0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': -15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 707.2,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': -154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 6,
              teamId: 200,
              championId: 82,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                participantId: 6,
                win: true,
                item0: 1056,
                item1: 4633,
                item2: 3020,
                item3: 3115,
                item4: 1011,
                item5: 1026,
                item6: 3340,
                kills: 1,
                deaths: 5,
                assists: 5,
                largestKillingSpree: 0,
                largestMultiKill: 1,
                killingSprees: 0,
                longestTimeSpentLiving: 413,
                doubleKills: 0,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 45460,
                magicDamageDealt: 40168,
                physicalDamageDealt: 5291,
                trueDamageDealt: 0,
                largestCriticalStrike: 0,
                totalDamageDealtToChampions: 2988,
                magicDamageDealtToChampions: 2803,
                physicalDamageDealtToChampions: 184,
                trueDamageDealtToChampions: 0,
                totalHeal: 3516,
                totalUnitsHealed: 1,
                damageSelfMitigated: 10335,
                damageDealtToObjectives: 11250,
                damageDealtToTurrets: 4146,
                visionScore: 13,
                timeCCingOthers: 1,
                totalDamageTaken: 17834,
                magicalDamageTaken: 9446,
                physicalDamageTaken: 8036,
                trueDamageTaken: 351,
                goldEarned: 10664,
                goldSpent: 9550,
                turretKills: 1,
                inhibitorKills: 0,
                totalMinionsKilled: 39,
                neutralMinionsKilled: 8,
                neutralMinionsKilledTeamJungle: 8,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 1,
                champLevel: 13,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 9,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: true,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8010,
                perk0Var1: 0,
                perk0Var2: 0,
                perk0Var3: 0,
                perk1: 9111,
                perk1Var1: 420,
                perk1Var2: 120,
                perk1Var3: 0,
                perk2: 9105,
                perk2Var1: 18,
                perk2Var2: 0,
                perk2Var3: 0,
                perk3: 8299,
                perk3Var1: 125,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8135,
                perk4Var1: 930,
                perk4Var2: 4,
                perk4Var3: 0,
                perk5: 8139,
                perk5Var1: 230,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8000,
                perkSubStyle: 8100,
                statPerk0: 5005,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 6,
                creepsPerMinDeltas: {
                  '0-10': 2.9000000000000004,
                },
                xpPerMinDeltas: {
                  '0-10': 364.8,
                },
                goldPerMinDeltas: {
                  '0-10': 449.3,
                },
                csDiffPerMinDeltas: {
                  '0-10': -0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': 15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 446.5,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': 154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 7,
              teamId: 200,
              championId: 28,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                participantId: 7,
                win: true,
                item0: 4630,
                item1: 4636,
                item2: 3100,
                item3: 4628,
                item4: 3020,
                item5: 3089,
                item6: 3340,
                kills: 15,
                deaths: 6,
                assists: 9,
                largestKillingSpree: 5,
                largestMultiKill: 2,
                killingSprees: 4,
                longestTimeSpentLiving: 495,
                doubleKills: 3,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 81004,
                magicDamageDealt: 76318,
                physicalDamageDealt: 3765,
                trueDamageDealt: 920,
                largestCriticalStrike: 0,
                totalDamageDealtToChampions: 28520,
                magicDamageDealtToChampions: 27400,
                physicalDamageDealtToChampions: 659,
                trueDamageDealtToChampions: 460,
                totalHeal: 3448,
                totalUnitsHealed: 1,
                damageSelfMitigated: 14973,
                damageDealtToObjectives: 10318,
                damageDealtToTurrets: 1699,
                visionScore: 16,
                timeCCingOthers: 5,
                totalDamageTaken: 23494,
                magicalDamageTaken: 7761,
                physicalDamageTaken: 13966,
                trueDamageTaken: 1766,
                goldEarned: 15964,
                goldSpent: 16050,
                turretKills: 1,
                inhibitorKills: 0,
                totalMinionsKilled: 75,
                neutralMinionsKilled: 16,
                neutralMinionsKilledTeamJungle: 8,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 28,
                champLevel: 18,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 9,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: true,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 1,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8128,
                perk0Var1: 1385,
                perk0Var2: 22,
                perk0Var3: 0,
                perk1: 8143,
                perk1Var1: 1120,
                perk1Var2: 0,
                perk1Var3: 0,
                perk2: 8138,
                perk2Var1: 30,
                perk2Var2: 0,
                perk2Var3: 0,
                perk3: 8105,
                perk3Var1: 13,
                perk3Var2: 5,
                perk3Var3: 0,
                perk4: 8224,
                perk4Var1: 886,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8236,
                perk5Var1: 48,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8100,
                perkSubStyle: 8200,
                statPerk0: 5008,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 7,
                creepsPerMinDeltas: {
                  '0-10': 6.199999999999999,
                },
                xpPerMinDeltas: {
                  '0-10': 511.9,
                },
                goldPerMinDeltas: {
                  '0-10': 620.3,
                },
                csDiffPerMinDeltas: {
                  '0-10': -0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': 15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 663,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': 154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 8,
              teamId: 200,
              championId: 29,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                participantId: 8,
                win: true,
                item0: 3006,
                item1: 6672,
                item2: 6676,
                item3: 3153,
                item4: 3086,
                item5: 1042,
                item6: 3340,
                kills: 9,
                deaths: 6,
                assists: 9,
                largestKillingSpree: 3,
                largestMultiKill: 2,
                killingSprees: 3,
                longestTimeSpentLiving: 383,
                doubleKills: 1,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 84858,
                magicDamageDealt: 502,
                physicalDamageDealt: 73066,
                trueDamageDealt: 11290,
                largestCriticalStrike: 597,
                totalDamageDealtToChampions: 20720,
                magicDamageDealtToChampions: 502,
                physicalDamageDealtToChampions: 16035,
                trueDamageDealtToChampions: 4182,
                totalHeal: 1753,
                totalUnitsHealed: 1,
                damageSelfMitigated: 5649,
                damageDealtToObjectives: 28471,
                damageDealtToTurrets: 11794,
                visionScore: 17,
                timeCCingOthers: 8,
                totalDamageTaken: 14724,
                magicalDamageTaken: 5827,
                physicalDamageTaken: 8020,
                trueDamageTaken: 875,
                goldEarned: 14532,
                goldSpent: 12200,
                turretKills: 4,
                inhibitorKills: 1,
                totalMinionsKilled: 56,
                neutralMinionsKilled: 12,
                neutralMinionsKilledTeamJungle: 0,
                neutralMinionsKilledEnemyJungle: 4,
                totalTimeCrowdControlDealt: 400,
                champLevel: 17,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 12,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: true,
                firstTowerAssist: false,
                firstInhibitorKill: true,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 1,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 9923,
                perk0Var1: 49,
                perk0Var2: 96,
                perk0Var3: 0,
                perk1: 8143,
                perk1Var1: 535,
                perk1Var2: 0,
                perk1Var3: 0,
                perk2: 8138,
                perk2Var1: 18,
                perk2Var2: 0,
                perk2Var3: 0,
                perk3: 8135,
                perk3Var1: 1578,
                perk3Var2: 5,
                perk3Var3: 0,
                perk4: 9104,
                perk4Var1: 14,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8014,
                perk5Var1: 400,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8100,
                perkSubStyle: 8000,
                statPerk0: 5005,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 8,
                creepsPerMinDeltas: {
                  '0-10': 2.9,
                },
                xpPerMinDeltas: {
                  '0-10': 413,
                },
                goldPerMinDeltas: {
                  '0-10': 552.3,
                },
                csDiffPerMinDeltas: {
                  '0-10': -0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': 15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 447.8,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': 154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 9,
              teamId: 200,
              championId: 12,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                participantId: 9,
                win: true,
                item0: 3047,
                item1: 6662,
                item2: 3075,
                item3: 3053,
                item4: 3083,
                item5: 2055,
                item6: 3340,
                kills: 5,
                deaths: 8,
                assists: 18,
                largestKillingSpree: 3,
                largestMultiKill: 2,
                killingSprees: 2,
                longestTimeSpentLiving: 261,
                doubleKills: 1,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 72144,
                magicDamageDealt: 60051,
                physicalDamageDealt: 10538,
                trueDamageDealt: 1554,
                largestCriticalStrike: 16,
                totalDamageDealtToChampions: 14202,
                magicDamageDealtToChampions: 11102,
                physicalDamageDealtToChampions: 1613,
                trueDamageDealtToChampions: 1487,
                totalHeal: 8154,
                totalUnitsHealed: 5,
                damageSelfMitigated: 42498,
                damageDealtToObjectives: 8430,
                damageDealtToTurrets: 5766,
                visionScore: 16,
                timeCCingOthers: 42,
                totalDamageTaken: 35387,
                magicalDamageTaken: 8233,
                physicalDamageTaken: 21411,
                trueDamageTaken: 5742,
                goldEarned: 14084,
                goldSpent: 13675,
                turretKills: 0,
                inhibitorKills: 1,
                totalMinionsKilled: 70,
                neutralMinionsKilled: 0,
                neutralMinionsKilledTeamJungle: 0,
                neutralMinionsKilledEnemyJungle: 0,
                totalTimeCrowdControlDealt: 1350,
                champLevel: 17,
                visionWardsBoughtInGame: 1,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 10,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8437,
                perk0Var1: 824,
                perk0Var2: 598,
                perk0Var3: 0,
                perk1: 8446,
                perk1Var1: 3050,
                perk1Var2: 0,
                perk1Var3: 0,
                perk2: 8444,
                perk2Var1: 2042,
                perk2Var2: 0,
                perk2Var3: 0,
                perk3: 8451,
                perk3Var1: 231,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8347,
                perk4Var1: 0,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8321,
                perk5Var1: 2,
                perk5Var2: 0,
                perk5Var3: 0,
                perkPrimaryStyle: 8400,
                perkSubStyle: 8300,
                statPerk0: 5008,
                statPerk1: 5003,
                statPerk2: 5003,
              },
              timeline: {
                participantId: 9,
                creepsPerMinDeltas: {
                  '0-10': 1.3,
                },
                xpPerMinDeltas: {
                  '0-10': 445.1,
                },
                goldPerMinDeltas: {
                  '0-10': 543.1,
                },
                csDiffPerMinDeltas: {
                  '0-10': -0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': 15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 1048.1,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': 154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
            {
              participantId: 10,
              teamId: 200,
              championId: 23,
              spell1Id: 4,
              spell2Id: 1,
              stats: {
                participantId: 10,
                win: true,
                item0: 6671,
                item1: 3006,
                item2: 6676,
                item3: 3072,
                item4: 3508,
                item5: 3046,
                item6: 3340,
                kills: 20,
                deaths: 13,
                assists: 4,
                largestKillingSpree: 4,
                largestMultiKill: 2,
                killingSprees: 6,
                longestTimeSpentLiving: 155,
                doubleKills: 5,
                tripleKills: 0,
                quadraKills: 0,
                pentaKills: 0,
                unrealKills: 0,
                totalDamageDealt: 135622,
                magicDamageDealt: 3656,
                physicalDamageDealt: 130304,
                trueDamageDealt: 1661,
                largestCriticalStrike: 918,
                totalDamageDealtToChampions: 33858,
                magicDamageDealtToChampions: 2456,
                physicalDamageDealtToChampions: 29740,
                trueDamageDealtToChampions: 1661,
                totalHeal: 4432,
                totalUnitsHealed: 1,
                damageSelfMitigated: 44305,
                damageDealtToObjectives: 22625,
                damageDealtToTurrets: 8194,
                visionScore: 2,
                timeCCingOthers: 1,
                totalDamageTaken: 29495,
                magicalDamageTaken: 3893,
                physicalDamageTaken: 21198,
                trueDamageTaken: 4403,
                goldEarned: 19459,
                goldSpent: 19360,
                turretKills: 3,
                inhibitorKills: 1,
                totalMinionsKilled: 113,
                neutralMinionsKilled: 12,
                neutralMinionsKilledTeamJungle: 0,
                neutralMinionsKilledEnemyJungle: 12,
                totalTimeCrowdControlDealt: 13,
                champLevel: 17,
                visionWardsBoughtInGame: 0,
                sightWardsBoughtInGame: 0,
                wardsPlaced: 2,
                wardsKilled: 0,
                firstBloodKill: false,
                firstBloodAssist: false,
                firstTowerKill: false,
                firstTowerAssist: false,
                firstInhibitorKill: false,
                firstInhibitorAssist: false,
                combatPlayerScore: 0,
                objectivePlayerScore: 0,
                totalPlayerScore: 0,
                totalScoreRank: 0,
                playerScore0: 0,
                playerScore1: 0,
                playerScore2: 0,
                playerScore3: 0,
                playerScore4: 0,
                playerScore5: 0,
                playerScore6: 0,
                playerScore7: 0,
                playerScore8: 0,
                playerScore9: 0,
                perk0: 8008,
                perk0Var1: 1,
                perk0Var2: 10,
                perk0Var3: 0,
                perk1: 9101,
                perk1Var1: 3524,
                perk1Var2: 3204,
                perk1Var3: 0,
                perk2: 9104,
                perk2Var1: 8,
                perk2Var2: 30,
                perk2Var3: 0,
                perk3: 8014,
                perk3Var1: 875,
                perk3Var2: 0,
                perk3Var3: 0,
                perk4: 8139,
                perk4Var1: 1015,
                perk4Var2: 0,
                perk4Var3: 0,
                perk5: 8135,
                perk5Var1: 2711,
                perk5Var2: 5,
                perk5Var3: 0,
                perkPrimaryStyle: 8000,
                perkSubStyle: 8100,
                statPerk0: 5008,
                statPerk1: 5008,
                statPerk2: 5002,
              },
              timeline: {
                participantId: 10,
                creepsPerMinDeltas: {
                  '0-10': 5.6,
                },
                xpPerMinDeltas: {
                  '0-10': 461.9,
                },
                goldPerMinDeltas: {
                  '0-10': 789,
                },
                csDiffPerMinDeltas: {
                  '0-10': -0.6600000000000006,
                },
                xpDiffPerMinDeltas: {
                  '0-10': 15.97999999999999,
                },
                damageTakenPerMinDeltas: {
                  '0-10': 958.4000000000001,
                },
                damageTakenDiffPerMinDeltas: {
                  '0-10': 154.9799999999999,
                },
                role: 'DUO_SUPPORT',
                lane: 'NONE',
              },
            },
          ],
          participantIdentities: [
            {
              participantId: 1,
              player: {
                platformId: 'NA1',
                accountId: 'Db1ZTAXvNc9hOYWmUMzkR9xutsicnFl-I2VahxEVg3UhEg',
                summonerName: 'TEEHEE92',
                summonerId: 'AO6ZPCTlqXAL2L3v9wAiv_HhiPzMFoyQ01sCBah3qa39e1o',
                currentPlatformId: 'NA1',
                currentAccountId: 'Db1ZTAXvNc9hOYWmUMzkR9xutsicnFl-I2VahxEVg3UhEg',
                matchHistoryUri: '/v1/stats/player_history/NA1/41959134',
                profileIcon: 4589,
              },
            },
            {
              participantId: 2,
              player: {
                platformId: 'NA1',
                accountId: 'x06bX1WptYKoriZp-GciPM65O03KoKPdUQoiNXhYw4YrBe8',
                summonerName: 'MrBabbit',
                summonerId: 'XMz-M35V13ybVKwKL5U7Nw9hzVQ2DjjtlyAZ_O5NNTIvLGw',
                currentPlatformId: 'NA1',
                currentAccountId: 'x06bX1WptYKoriZp-GciPM65O03KoKPdUQoiNXhYw4YrBe8',
                matchHistoryUri: '/v1/stats/player_history/NA1/218104782',
                profileIcon: 4569,
              },
            },
            {
              participantId: 3,
              player: {
                platformId: 'NA1',
                accountId: 'iQ2ONYVtNV5t0OYGOz3BnLVn5xpPXOu3fGGGHysFmFQerAk',
                summonerName: 'Podeleon',
                summonerId: 'gCQ7WMgnMyoj8KMprejCl3s1MA9n1uNWH7oRBv-XjaDlUh0',
                currentPlatformId: 'NA1',
                currentAccountId: 'iQ2ONYVtNV5t0OYGOz3BnLVn5xpPXOu3fGGGHysFmFQerAk',
                matchHistoryUri: '/v1/stats/player_history/NA1/231177505',
                profileIcon: 1133,
              },
            },
            {
              participantId: 4,
              player: {
                platformId: 'NA1',
                accountId: 'BT8yHSDLzXr_T8GU1eEKaBs75eOnx1i9hRJ4mmZEDoUFiHriPp7NhUIg',
                summonerName: 'Smokeyroo',
                summonerId: 'tm3nSsI0acqrjvueR9dpvDGiz_vAnj5pIK4yJr_x9jFpcnAJ',
                currentPlatformId: 'NA1',
                currentAccountId: 'BT8yHSDLzXr_T8GU1eEKaBs75eOnx1i9hRJ4mmZEDoUFiHriPp7NhUIg',
                matchHistoryUri: '/v1/stats/player_history/NA1/2559424365733824',
                profileIcon: 1385,
              },
            },
            {
              participantId: 5,
              player: {
                platformId: 'NA1',
                accountId: '5HjdgBQvrg5-8MnYayWG2hnu9HBcEhV4XtuSlBmlobga_azWdaz6urqN',
                summonerName: 'ElijahIG',
                summonerId: 'D1r0osUcjallvXs_u7gtYFkkEwj0zPotkQFmUKkm2ZH4uHx6',
                currentPlatformId: 'NA1',
                currentAccountId: '5HjdgBQvrg5-8MnYayWG2hnu9HBcEhV4XtuSlBmlobga_azWdaz6urqN',
                matchHistoryUri: '/v1/stats/player_history/NA1/2297260647484288',
                profileIcon: 4792,
              },
            },
            {
              participantId: 6,
              player: {
                platformId: 'NA1',
                accountId: 'miCYMBj0i3-uy3CrmpBcp7Hxm43u7zIaOzmhRfafmZX4mrRynIXOZGyf',
                summonerName: 'Tr4pK1ng',
                summonerId: '5J76DfMawYvuOA3Zj8KVAeDnP5O1ph1bczOXXIRlBy5Fe54P',
                currentPlatformId: 'NA1',
                currentAccountId: 'miCYMBj0i3-uy3CrmpBcp7Hxm43u7zIaOzmhRfafmZX4mrRynIXOZGyf',
                matchHistoryUri: '/v1/stats/player_history/NA1/2124214780258944',
                profileIcon: 4644,
              },
            },
            {
              participantId: 7,
              player: {
                platformId: 'NA1',
                accountId: 'VkDNsxXBy3E3yPLRX23TYNMerTNLz4FlAstOkse7KcXmUNX8Co7K2Yjg',
                summonerName: 'LunariDescent',
                summonerId: 'mV3QIluOtdt8jHDgSwRq7daJyookMogLudtNUY4x1kzYEQOk',
                currentPlatformId: 'NA1',
                currentAccountId: 'VkDNsxXBy3E3yPLRX23TYNMerTNLz4FlAstOkse7KcXmUNX8Co7K2Yjg',
                matchHistoryUri: '/v1/stats/player_history/NA1/2063843494152832',
                profileIcon: 4659,
              },
            },
            {
              participantId: 8,
              player: {
                platformId: 'NA1',
                accountId: 'Eh6Q-VCoKdkV5rybi4Uzy0U8l3h-Pi2p7TMDE7fseUwmheo',
                summonerName: 'Naoto Shirogane',
                summonerId: 'Ay3SVi2l06dKmKQ-Jsrlb_Z6NKgcBJOjcCaYuHGHWzxC6w8',
                currentPlatformId: 'NA1',
                currentAccountId: 'Eh6Q-VCoKdkV5rybi4Uzy0U8l3h-Pi2p7TMDE7fseUwmheo',
                matchHistoryUri: '/v1/stats/player_history/NA1/214416224',
                profileIcon: 4852,
              },
            },
            {
              participantId: 9,
              player: {
                platformId: 'NA',
                accountId: '3WqCKUpSwxraHimHoxqAWf-VybUZDmAypuUbizwQfVQuBw',
                summonerName: 'RayneF1re',
                summonerId: 'bhN8fjG6dQTBsBLZCYcP9wr7scNQaEO9t9P42XyytrXGj5I',
                currentPlatformId: 'NA1',
                currentAccountId: '3WqCKUpSwxraHimHoxqAWf-VybUZDmAypuUbizwQfVQuBw',
                matchHistoryUri: '/v1/stats/player_history/NA/32865740',
                profileIcon: 4249,
              },
            },
            {
              participantId: 10,
              player: {
                platformId: 'NA1',
                accountId: 'W2MtSw_p4gulSUZbEQhS5v8euuPvwjAhHRYqkf7cDfJI2z0',
                summonerName: 'Sephian',
                summonerId: 'bKCCmCn6VtgC0DJ94YGdJWUvnQv65Xh3cT90-BdlAA0kGXM',
                currentPlatformId: 'NA1',
                currentAccountId: 'W2MtSw_p4gulSUZbEQhS5v8euuPvwjAhHRYqkf7cDfJI2z0',
                matchHistoryUri: '/v1/stats/player_history/NA1/211524347',
                profileIcon: 691,
              },
            },
          ],
        },
      })),
    },
    timeline: {
      get: jest.fn(),
    },
  },
};

export default riotAPI;
